# Generated by Django 5.2.17 on 2026-09-28 06:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('field_type', models.CharField(default='text', max_length=40)),
                ('placeholder', models.CharField(blank=True, max_length=180)),
                ('options', models.TextField(blank=True)),
                ('required', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=180)),
                ('value', models.TextField(blank=True)),
                ('group_name', models.CharField(default='homepage', max_length=80)),
                ('input_type', models.CharField(default='textarea', max_length=30)),
                ('sort_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=24, unique=True)),
                ('details', models.JSONField()),
                ('spam_key', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('email_status', models.CharField(default='pending', max_length=24)),
                ('email_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('submission_token', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name_plural': 'quote inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryThrottle',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('window_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('path', models.CharField(max_length=180)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_button', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.CharField(blank=True, max_length=220)),
                ('body', models.TextField(help_text='Separate sections with a blank line. For FAQ/process/add-ons, use the first line as the heading.')),
                ('cta_text', models.CharField(blank=True, max_length=80)),
                ('cta_link', models.CharField(blank=True, max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excerpt', models.CharField(max_length=320)),
                ('body', models.TextField()),
                ('image_path', models.CharField(blank=True, max_length=240)),
                ('image', models.ImageField(blank=True, upload_to='posts/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('summary', models.CharField(max_length=280)),
                ('details', models.TextField(help_text='Single source for package prices, duration, size limits and inclusions on the homepage, services page and detail page.')),
                ('highlight', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='SG AllClean', max_length=140)),
                ('tagline', models.CharField(max_length=220)),
                ('hero_title', models.CharField(max_length=220)),
                ('hero_subtitle', models.TextField()),
                ('intro_title', models.CharField(max_length=220)),
                ('intro_body', models.TextField()),
                ('contact_email', models.EmailField(blank=True, help_text='Hidden until PUBLIC_EMAIL_VERIFIED=true in .env.', max_length=254)),
                ('contact_phone', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=140)),
                ('coverage', models.CharField(max_length=220)),
                ('investment_note', models.TextField(blank=True, help_text='Legacy internal note; never displayed publicly.')),
                ('logo_path', models.CharField(blank=True, max_length=240)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='InquiryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.inquiry')),
            ],
        ),
    ]
