# Generated by Django 5.2.17 on 2026-09-30 07:06

import django.core.validators
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_hold_scaffold_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoginThrottle',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('window_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='navitem',
            name='path',
            field=models.CharField(max_length=180, validators=[website.models.validate_internal_path]),
        ),
        migrations.AlterField(
            model_name='page',
            name='cta_link',
            field=models.CharField(blank=True, max_length=180, validators=[website.models.validate_internal_path]),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), website.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), website.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_path',
            field=models.CharField(blank=True, max_length=240, validators=[website.models.validate_internal_path]),
        ),
    ]
